apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mercuryhealth-prod
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: mercuryhealth-prod
    spec:
      containers:
      - name: mercuryhealth-prod
        image: acrjdtest.azurecr.io/mercuryhealthapi:latest
        env:
        - name: Local
          value: "false"
        - name: ASPNETCORE_URLS
          value: "http://+:80"        
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: jenkinsjd
---
apiVersion: v1
kind: Service
metadata:
  name: mercuryhealth-prod
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: mercuryhealth-prod
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mercuryhealth-prod-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: mercuryhealth-prod.k8s.az.jessicadeen.com
      http:
        paths:
          - backend:
              serviceName: mercuryhealth-prod
              servicePort: 80
  tls:
    - secretName: mercuryhealth-prod.k8s.az.jessicadeen.com
      hosts:
      - mercuryhealth-prod.k8s.az.jessicadeen.com